name: Sync Fork with Main

on:
  push:
    branches: ['main']

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with: 
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0
          ref: main

      - name: Add remote-url
        run: |
          git remote add forked-repo https://yereong:${{ secrets.AUTO_ACTIONS }}@github.com/yereong/2025_UNITHON_TEAM_11_FE
          git config user.name yereong
          git config user.email lily030624@gmail.com
      
      - name: Push changes to forked-repo 
        run: |
          git push -f forked-repo main
      
      - name: Clean up
        run: |
          git remote remove forked-repo